### ISSUE TITLE
Cutting the number of scissor cuts

### ISSUE THREAD

**Issue by merland** [btcguide/btcguide.github.io#3]
Regarding  [cutting 2048 pieces of paper](https://github.com/btcguide/btcguide.github.io/blob/master/_pages/setup-wallets/paper.md#cut-out-seed-words): Cutting all of them would take a looong time. And the pieces would become really miniscule. 

Would you consider linking to the [SeedPicker cutouts](https://github.com/merland/seedpicker/blob/master/guide/GUIDE.md) instead, to decrease the number of pieces to 342? Full entropy is achieved using a look-up table and one six-side die.  
You could also just copy them over here if you like.

**Comment by mflaxman** [comment]
I like the cutouts (it's more elegant!), but I think it's more complicated for the average user. The ultimate goal is for packs of 2048 words (already cut out) to be included by HW wallet manufactures with their wallets, sold on sites like Amazon, and even sold over lightning. If you have a paper cutter and a  large single single sheet of paper (see issue #2), then it's only 11 cuts. Not ideal but not terrible either.

For advanced users, I think it makes a lot of sense. I've added them here (commit [here](https://github.com/btcguide/btcguide.github.io/commit/cccaecd4157e8dbbfa13d3a683e92b2d79d39ab1), revisions welcome):
https://btcguide.github.io/setup-wallets/paper-advanced#use-seedpicker-cutouts

**Comment by merland** [comment]
Fair enough, these are some hard tradeoffs. I have spent more hours than I'd like to admit on how to do this the best way. 
One problem with having pre-made packs of cards or paper slips is that it would be tedious to verify - between sessions - that an attacker has not switched some of them to offset the probability in their favor. 
One idea I had was to have a large pre-printed, framed horizontal "poster" with all the words, and roll a metal or glass ball over it, then choose the word where the ball stops. But that has its own challenges, e.g. how to place the words to get exactly the same probability for every word. :)

**Comment by mflaxman** [comment]
`log(2048**23,2)` is 253 bits of entropy. If the list contains any false words, decent software (like seedpicker) will trivially catch it.

If the list contains the same words repeated a few times, the entropy here is still massive. Let's say it's secretly only 128 words (each repeated 16x), and you somehow don't catch that because you don't thoroughly inspect them. `log(128**23,2)` is still 161 bits of entropy.

In other words, even someone with a poor understanding of cryptography should be able to count that there are indeed 2048 words in the bag and that alone is sufficient to say attacking this is incredibly hard (especially if it's part of a multisig scheme where you need to get >1 seeds to steal funds).

To me, the next obvious defense is to sell the words in alphabetical order (kind of like a new deck of cards). That should make it easier for the person inspecting the words to verify they're legit. Of course you have to shake your bag of words up thoroughly now, but again that's a meatspace cryptography problem that most people intuitively understand (like shuffling a deck of cards).

If anything, there's a strong defense of _lowering_ the length of the default seed phrase to something like 16 words. But, once you're at the point where you're etching something in metal, the tiny bit extra of metal is probably well worth the being able to sleep at night part.
