### ISSUE TITLE
Why Multisig?

### ISSUE THREAD

**Issue by BitcoinLixin** [btcguide/btcguide.github.io#45]
https://btcguide.github.io/why-multisig

“The goal of this guide is to achieve a basic multisig: a 2-of-3 signature scheme using (at least) two different hardware wallets made by different manufacturers.”

My colleague was translating this part and she asked me - why 2 hardware wallets can set up a 2-3 multi-sig? (She hasn't read the following chapters when she asked this)
I think this description here may confuse some average users like her.

@mflaxman Hope you don't feel I am too picky haha. Just wanna share a perspective from a normal user.

**Comment by mflaxman** [comment]
Is this better now? Please reopen if you think still unclear:
https://github.com/btcguide/btcguide.github.io/commit/cde993e4893e6437df9ca1de32b00de3324171fa

I'm kind of hand-wavy in the non-advanced sections, because I don't want to get people held up on perfection, having to buy 3 devices (2 is sufficient to start), and I think the lack of decent hardware wallets right now is a big issue (that will hopefully improve dramatically soon).

**Comment by mflaxman** [comment]
I appreciate github issues/comments btw, this stuff is tricky to explain clearly.
